name = "guess-word-puzzle"
compatibility_date = "2024-01-01"
pages_build_output_dir = "packages/client/dist"

[build]
command = "pnpm install && pnpm --filter common build && pnpm --filter client build"

[vars]
VITE_API_URL = "http://localhost:3000/api"
