name = "guess-word-puzzle"
main = "dist/index.js"
compatibility_date = "2024-01-01"

[dev]
port = 3000
local_protocol = "http"

[[d1_databases]]
binding = "DB"
database_name = "guess-word-puzzle-db"
database_id = "local-dev"
migrations_dir = "drizzle"
