name = "guess-word-puzzle"
main = "dist/index.js"
compatibility_date = "2024-01-01"

[dev]
port = 3000
local_protocol = "http"

[[d1_databases]]
binding = "DB"
database_name = "guess-word-puzzle-db"
database_id = "ec363f65-0938-4725-a336-98b863ddcae1"
migrations_dir = "drizzle"
